import { MovieProject } from "@/lib/types/domain";
import { STORY_CATEGORIES, DIRECTOR_STYLES, DESK_PHOTOS } from "@/lib/sample-data";

export const DEFAULT_ARCHIVE_PROJECTS: MovieProject[] = [
  {
    id: "proj_college_years",
    userId: "user_demo",
    title: "THE LAST FOUR YEARS",
    category: STORY_CATEGORIES[0], // College
    style: DIRECTOR_STYLES[4], // Coming of Age
    description: "The 2am library marathons, leaky hostel roofs, and the four friends who made a city feel like home.",
    privacy: "public",
    status: "ready",
    createdAt: "2026-05-18T10:00:00Z",
    updatedAt: "2026-05-18T10:30:00Z",
    publicShareId: "college-years-2026",
    memories: [
      {
        id: "mem_1",
        projectId: "proj_college_years",
        type: "photo",
        url: DESK_PHOTOS[0].imageUrl,
        thumbnailUrl: DESK_PHOTOS[0].imageUrl,
        caption: "First day move-in. Boxes everywhere and trembling optimism.",
        date: "2022-08-15",
        location: "East Wing Dorms",
        people: ["Rohan", "Maya"],
        order: 1,
        aspect: "aspect-4/3",
        rotation: -2,
      },
      {
        id: "mem_2",
        projectId: "proj_college_years",
        type: "photo",
        url: DESK_PHOTOS[1].imageUrl,
        thumbnailUrl: DESK_PHOTOS[1].imageUrl,
        caption: "The terrace bonfire during final semester submissions.",
        date: "2024-03-20",
        location: "Old Town Rooftop",
        people: ["Maya", "Kabir", "Rohan"],
        order: 2,
        aspect: "aspect-4/3",
        rotation: 1.5,
      },
      {
        id: "mem_3",
        projectId: "proj_college_years",
        type: "photo",
        url: DESK_PHOTOS[4].imageUrl,
        thumbnailUrl: DESK_PHOTOS[4].imageUrl,
        caption: "Throwing caps into the golden hour wind.",
        date: "2026-05-14",
        location: "Main Quadrangle",
        people: ["Maya", "Rohan", "Kabir", "Ananya"],
        order: 3,
        aspect: "aspect-21/9",
        rotation: 0.5,
      },
    ],
    interview: {
      about: "Four college roommates surviving university in a new city.",
      people: "Maya, Rohan, Kabir, and Ananya.",
      unforgettableMoment: "The midnight tea runs on foggy December nights.",
      hardestMoment: "Third year winter when Maya almost dropped out.",
      turningPoint: "When we decided to live together in an off-campus apartment.",
      endingFeeling: "nostalgic",
    },
    storyOutline: {
      logline: "Four strangers in dorm room 302 become an unbreakable family across four relentless years.",
      theme: "Growing up isn't leaving people behind; it's carrying them into whatever comes next.",
      actStructure: [
        {
          id: "act_1",
          chapterNumber: 1,
          title: "The Unpacked Suitcases",
          handwrittenBeat: "Strangers in an empty hallway.",
          synopsis: "The awkward silence of moving in turns into our first shared meal on cardboard boxes.",
          targetTone: "Quiet & Tentative",
          associatedMemoryIds: ["mem_1"],
        },
        {
          id: "act_2",
          chapterNumber: 2,
          title: "The Midnight Routine",
          handwrittenBeat: "Surviving on chai & cheap printouts.",
          synopsis: "Exam seasons, forgotten deadlines, and discovering who stays awake with you.",
          targetTone: "Warm & Frenetic",
          associatedMemoryIds: ["mem_2"],
        },
        {
          id: "act_3",
          chapterNumber: 3,
          title: "The Storm in Winter",
          handwrittenBeat: "When the real world started knocking.",
          synopsis: "Doubt, pressure from parents, and the quiet promise to see each other through.",
          targetTone: "Vulnerable & Poignant",
          associatedMemoryIds: ["mem_2"],
        },
        {
          id: "act_4",
          chapterNumber: 4,
          title: "The Final Semester",
          handwrittenBeat: "Counting the remaining sunsets.",
          synopsis: "Packing up four years of memories into dusty cardboard boxes once again.",
          targetTone: "Bittersweet",
          associatedMemoryIds: ["mem_3"],
        },
        {
          id: "act_5",
          chapterNumber: 5,
          title: "Into the Wind",
          handwrittenBeat: "We were young, and we were invincible.",
          synopsis: "Standing on the quad, looking back one last time before stepping forward.",
          targetTone: "Triumphant & Nostalgic",
          associatedMemoryIds: ["mem_3"],
        },
      ],
    },
    scenes: [
      {
        id: "scene_1",
        order: 1,
        title: "DORMITORY 302",
        description: "Unpacking the first cardboard box in the August sunlight.",
        mediaId: "mem_1",
        mediaUrl: DESK_PHOTOS[0].imageUrl,
        voiceover: "We arrived with two suitcases and the terrifying belief that we knew where we were going.",
        durationSec: 4.5,
        transition: "fade",
        subtitle: "August 2022 • The beginning of something irreversible.",
        cameraMovement: "slow_zoom_in",
      },
      {
        id: "scene_2",
        order: 2,
        title: "ROOFTOP CHRONICLES",
        description: "Singing old melodies around a makeshift bonfire at 2:30am.",
        mediaId: "mem_2",
        mediaUrl: DESK_PHOTOS[1].imageUrl,
        voiceover: "The world outside was screaming with deadlines, but up here, time forgot about us.",
        durationSec: 5.0,
        transition: "crossfade",
        subtitle: "March 2024 • Chai, smoke, and quiet promises.",
        cameraMovement: "pan_right",
      },
      {
        id: "scene_3",
        order: 3,
        title: "THE LAST FRAME",
        description: "Four graduation caps caught against the golden horizon.",
        mediaId: "mem_3",
        mediaUrl: DESK_PHOTOS[4].imageUrl,
        voiceover: "You don't realize a chapter is ending until you're already standing on the other side.",
        durationSec: 6.0,
        transition: "film_burn",
        subtitle: "May 2026 • We made it.",
        cameraMovement: "subtle_drift",
      },
    ],
  },
  {
    id: "proj_goa_story",
    userId: "user_demo",
    title: "OUR GOA STORY",
    category: STORY_CATEGORIES[4], // Travel
    style: DIRECTOR_STYLES[2], // Nostalgia
    description: "Rented scooters, monsoon rains, and unmapped beaches with no cellular reception.",
    privacy: "public",
    status: "ready",
    createdAt: "2026-06-10T14:00:00Z",
    updatedAt: "2026-06-10T15:10:00Z",
    publicShareId: "goa-story-2026",
    memories: [
      {
        id: "mem_goa_1",
        projectId: "proj_goa_story",
        type: "photo",
        url: DESK_PHOTOS[2].imageUrl,
        thumbnailUrl: DESK_PHOTOS[2].imageUrl,
        caption: "Waiting for the ferry as the monsoon clouds rolled in.",
        date: "2025-07-12",
        location: "Divar Island Ferry",
        people: ["Siddharth", "Tara"],
        order: 1,
        aspect: "aspect-4/3",
        rotation: -1,
      },
      {
        id: "mem_goa_2",
        projectId: "proj_goa_story",
        type: "photo",
        url: DESK_PHOTOS[3].imageUrl,
        thumbnailUrl: DESK_PHOTOS[3].imageUrl,
        caption: "The café with the broken jukebox and the best fish curry.",
        date: "2025-07-14",
        location: "Assagao",
        people: ["Tara"],
        order: 2,
        aspect: "aspect-4/3",
        rotation: 2,
      },
    ],
    interview: {
      about: "A spontaneous week-long escape to the coast during the heavy monsoon.",
      people: "Siddharth and Tara.",
      unforgettableMoment: "Getting drenched on the ferry while sharing roasted corn.",
      hardestMoment: "A flat tyre in the middle of a forest at dusk.",
      turningPoint: "Turning off our phones for three straight days.",
      endingFeeling: "romantic",
    },
    storyOutline: {
      logline: "Two souls lose their maps and discover each other along the rain-washed coast.",
      theme: "The best journeys are the ones where you leave the itinerary behind.",
      actStructure: [
        {
          id: "act_goa_1",
          chapterNumber: 1,
          title: "The Departure",
          handwrittenBeat: "Running from the city noise.",
          synopsis: "Boarding the overnight train with muddy backpacks.",
          targetTone: "Excited & Free",
          associatedMemoryIds: ["mem_goa_1"],
        },
        {
          id: "act_goa_2",
          chapterNumber: 2,
          title: "Rain on the Windshield",
          handwrittenBeat: "Wet roads & yellow headlights.",
          synopsis: "Cruising through the palm groves as the skies opened up.",
          targetTone: "Dreamy",
          associatedMemoryIds: ["mem_goa_1", "mem_goa_2"],
        },
        {
          id: "act_goa_3",
          chapterNumber: 3,
          title: "The Salt & The Tide",
          handwrittenBeat: "Where the road ended.",
          synopsis: "Standing on the cliff watching the Arabian sea swell.",
          targetTone: "Poetic",
          associatedMemoryIds: ["mem_goa_2"],
        },
      ],
    },
    scenes: [
      {
        id: "scene_goa_1",
        order: 1,
        title: "THE DIVAR CROSSING",
        description: "Monsoon mist rising over the river waters.",
        mediaId: "mem_goa_1",
        mediaUrl: DESK_PHOTOS[2].imageUrl,
        voiceover: "We didn't know the timetable. We just stood there, waiting for the water to carry us across.",
        durationSec: 5.0,
        transition: "fade",
        subtitle: "July 2025 • The island where time slowed down.",
        cameraMovement: "slow_zoom_in",
      },
    ],
  },
];
